default: &default
  adapter: postgresql
  encoding: unicode
  host:     <%= ENV.fetch("DB_HOST") %>
  port:     <%= ENV.fetch("DB_PORT") %>
  username: <%= ENV.fetch("DB_USER") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  pool:     5

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") %>
