version: "3.8"

services:
  db:
    build:
      context: ./db
    container_name: db
    ports:
      - "5432:5432"
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5001:5000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: db
      DB_USER: admin
      DB_PASSWORD: admin
    depends_on:
      - db