version: "3.8"

services:
  db:
    build:
      context: ./db
    container_name: db
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: db
      DB_USER: admin
      DB_PASSWORD: admin
    depends_on:
      - db
    volumes:
      - ./backend:/app
